### PR TITLE
Fixes #36

### LINKED ISSUE #36: Splashpage renders incorrectly on Windows

### PR DESCRIPTION
**Pull request by markhalonen**

### CODE REVIEW

**Comment by bhalonen** [comment]
Not working on my computer.
image

**Comment by markhalonen** [comment]
Hopefully is working now

**Comment by bhalonen** [comment]
It still is wrong on my screen, but Luke didn't have any problem. Might be a parallels thing. Going to call it good.

**Comment by markhalonen** [comment]
How did Luke test it?

**Comment by markhalonen** [comment]
It is probably not a parallels thing. I have not seen many issues like this.

**Comment by bhalonen** [comment]
He just used it

**Pull request merged**
