### PR TITLE
#24 Citations 

### PR DESCRIPTION
**Pull request by markhalonen**
For some reason I named the branch `references`. Will need to fetch the `references` branch on Processor, Viewer, and SPLibraries to test.

### CODE REVIEW

**Comment by bhalonen** [comment]
Going to figure out how to fetch branches and test today.

**Comment by bhalonen** [comment]
Mark, you should rebase or pull from main before making a pull request. I've needed to rebase a couple of times to fix the build. (Same path thing)

**Comment by bhalonen** [comment]
Did you merge in all of your changes? I'm not seeing the "showCitationDialog" in your commit...
```
    [javac] C:\Users\brent\git\SurePulseDataProcessor\build\build\src\net\relinc\processor\controllers\SplashPageController.java:201: error: cannot find symbol
    [javac] 		Dialogs.showCitationDialog();
    [javac] 		       ^
    [javac]   symbol:   method showCitationDialog()
    [javac]   location: class Dialogs
    [javac] Note: C:\Users\brent\git\SurePulseDataProcessor\build\build\src\net\relinc\processor\controllers\EditCell.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
```

**Comment by markhalonen** [comment]
That's [here](https://github.com/relinc/SPLibraries/commit/60427f23be0e903d9791d1766191e2017f467958) in the SPLibraries repo. So you'll have to fetch the `references` branch there

**Comment by bhalonen** [comment]
Add the same button in the export part of the  analysis section, and add a plain-text citation.

**Comment by bhalonen** [comment]
REL Inc. SURE-Pulse. https://github.com/relinc/SurePulseDataProcessor, 2015.

Change it to just REL Inc. as well.

**Comment by markhalonen** [comment]
I've added the requested [changes](https://github.com/relinc/SPLibraries/commit/0a0b12b30251ae76b8dcfe7228287cb5d617ce77)

**Pull request merged**
