### PR TITLE
Fixes Issue #16

### PR DESCRIPTION
**Pull request by markhalonen**

### CODE REVIEW

**Comment by bhalonen** [comment]
Why remove arrow key navigation? Confusing?

**Comment by markhalonen** [comment]
When the text field is selected, I want the arrow keys to operate on the selected text, not navigate away. Don't know why that was in there.

**Comment by markhalonen** [comment]
Except for the up and down arrows, that can be for navigation, but right and left should apply to text

**Comment by bhalonen** [comment]
I'm going to merge this, then pull it to make sure it works.

**Comment by markhalonen** [comment]
Ok, you can pull it before merging. You can get remote branches with `git fetch` I believe.

**Pull request merged**
