### PR TITLE
Lowpass filter arrows

### PR DESCRIPTION
**Pull request by markhalonen**
Kind of a PITA, changes on SurePulseDataProcessor, SPLibraries, and SurePulseDataViewer.
All branches are named `lowpass-filter-arrows`.
Fixes issue #19

### CODE REVIEW

**Comment by bhalonen** [comment]
I don't see it in the interface. This might be just a windows side problem.

**Comment by bhalonen** [comment]
Also, I needed to change the permissions on a variable from nothing to public. I might be using a newer version of Java than you. I'm using 9.0. What are you using?

**Comment by markhalonen** [comment]
You need to checkout `lowpass-filter-arrows` in SPLibraries. I store some GUI code in the SPLibraries project, I know I hesitated to do it but it's done. Checkout `lowpass-filter-arrows` across the 3 repos.

I think I'm on Java 8. Would probably be easy and worth it to upgrade.

**Comment by bhalonen** [comment]
image
Charcter set issue?

**Comment by markhalonen** [comment]
I fixed the arrow issue

**Pull request merged**
